services:
  fruit-classifier:
    build: .
    ports:
      - "5001:5000"
      - "8502:8501"
    devices:
      - "/dev/video0:/dev/video0"
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    environment:
      - PYTHONUNBUFFERED=1
      - DISPLAY=${DISPLAY}
    privileged: true